<?php
$max_len = LastLogins::$config['max_len']['value'];
$show_all_connected = LastLogins::$config['show_all_connected']['value'];

$num_active = array(
   'total' => 0,
   'rows' => 0
);

// format dates
if(!empty($data['list']))
foreach($data['list'] as $k => $access) {
   if(!isset($access['logout_date'])) {
      $num_active['total']++;
      $data['list'][$k]['last_login'] = "online";
   } else {
      //TO-DO: fix warning generated by 'date'
      @$data['list'][$k]['last_login'] =  dateDifference(date('UTC'),$access['logout_date']);
   }
}

//group duplicates
$access_list = array();
if(!empty($data['list']))
foreach($data['list'] as $i => $x) {
   $match_found = false;
   foreach($access_list as $j => $y) {
      if($x['user']==$y['user'] 
            && $x['host']==$y['host'] 
            && $x['last_login']==$y['last_login']) {
         $access_list[$j]['n']++;
         $match_found = true;
         break;
      } 
   }
   if(!$match_found)  {
      if(!isset($x['logout_date'])) $num_active['rows']++;
      $access_list[] = array(
         'user' => $x['user'],
         'host' => $x['host'],
         'last_login' => $x['last_login'],
         'online' => isset($x['logout_date'])? false:true,
         'n' => 1
      );
   }
}

// truncate access list
if( count($access_list) > $max_len ) {
   $splice_len = $max_len;

   if($show_all_connected)
      $splice_len = max($max_len, $num_active['rows']);

   array_splice($access_list, $splice_len );
}
?>
<div class="panel panel-default">
    <div class="panel-heading">Last Logins  
      <?php if($num_active['total']>0): ?>
         <span class="badge pull-right"><?php echo $num_active['total'] ?> online</span>
      <?php endif; ?>
    </div>
    <div class="panel-body">
       <table class="table table-condensed table-striped">
       <thead>
         <tr>
           <th>user</th>
           <th>host</th>
           <th>date</th>
         </tr>
       </thead>
       <?php if(count($data['list'])==0): ?>
          <tr><td colspan=2>no login history</td></tr>
          
       <?php else: foreach($access_list as $access): ?>
         <tr <?php if($access['online']) echo "class='success' "?> >
            <td><?php echo $access['user'] ?></td>
            <td><?php echo substr($access['host'],0,20)  ?></td>
            <td>
               <?php echo $access['last_login'] ?>
               <?php if($access['n']>1):?>
                  <span class='badge pull-right'>x<?php  echo $access['n'] ?></span>
               <?php endif ?>
            </td>
         </tr>
       <?php endforeach; endif; ?>
       </table>
    </div>
</div>
